### ISSUE TITLE
'Fachschaft07 has stopped."

### ISSUE THREAD

**Issue by thomai** [Fachschaft07/fs-app#53]
My steps are:
* Type in a study group in the timetable lesson selection
* Press the hardware 'back' button
* CRASH

I sent the report already via the Android default 'send report' functionality.

**Comment by FHellmann** [comment]
```java
java.lang.ArrayIndexOutOfBoundsException: length=7; index=-1
	at edu.hm.cs.fs.app.ui.timetable.structure.LessonCell.<init>(LessonCell.java:31)
	at edu.hm.cs.fs.app.ui.timetable.TimetableAdapter$GridManager.getCell(TimetableAdapter.java:262)
	at edu.hm.cs.fs.app.ui.timetable.TimetableAdapter.onBindViewHolder(TimetableAdapter.java:79)
	at edu.hm.cs.fs.app.ui.timetable.TimetableAdapter.onBindViewHolder(TimetableAdapter.java:39)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5277)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5310)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4568)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4461)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1962)
	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:438)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1334)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)
	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2847)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3145)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15678)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```
